<a href="https://colab.research.google.com/github/MajorSohaib/Data_Science_journey/blob/main/week2_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("Numpy ready!!!")

Numpy ready!!!


Array reshapping


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original shape: ", arr.shape)

arr_2d = arr.reshape(2, 3)
print("Reshaped array of 2x3 is: ")
print(arr_2d)

arr_3x2 = arr.reshape(3, 2)
print("Reshaped array of 3x2 is: ")
print(arr_3x2)


Original shape:  (6,)
Reshaped array of 2x3 is: 
[[1 2 3]
 [4 5 6]]
Reshaped array of 3x2 is: 
[[1 2]
 [3 4]
 [5 6]]


Autoshape





In [ ]:
arr = np.array([1,2, 3, 4, 5, 6])

auto_reshape = arr.reshape(2, -1)
print("The autoreshape is: ")
print(auto_reshape)
print(arr.shape)
print("Shape: ", auto_reshape.shape)

The autoreshape is: 
[[1 2 3]
 [4 5 6]]
(6,)
Shape:  (2, 3)


In [4]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

ages = df['Age'].dropna().to_numpy()

print("Type: ", type(ages))
print("Shape: ", ages.shape )
print("Mean age: ", round(np.mean(ages), 2))
print("Std of age: ", round(np.std(ages), 2))
print("Min age:", np.min(ages))
print("Max age: ", np.max(ages))


Type:  <class 'numpy.ndarray'>
Shape:  (714,)
Mean age:  29.7
Std of age:  14.52
Min age: 0.42
Max age:  80.0
