<a href="https://colab.research.google.com/github/MajorSohaib/Data_Science_journey/blob/main/week2_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)
print("Numpy ready")

2.0.2
Numpy ready


In [ ]:
scores_list = [23, 33,64, 88, 56]

#Numpy array
scores_array = np.array([23, 33,64, 88, 56])

print("List: ", scores_list)
print("Arrays: ", scores_array )
print("Datatype of list:", type(scores_list) )
print("Datatype of array: ", type(scores_array) )

List:  [23, 33, 64, 88, 56]
Arrays:  [23 33 64 88 56]
Datatype of list: <class 'list'>
Datatype of array:  <class 'numpy.ndarray'>


In [ ]:
#Numpy array
scores_array = np.array([23, 33,64, 88, 56])

print("Array + 10:", scores_array + 10)
print("Array * 2: ", scores_array * 2)
print("array Square: ", scores_array ** 2)

#this is goinng to give the error
'''scores_list = [23, 33,64, 88, 56]

print("list + 10:", scores_list + 10)
print("list * 2: ", scores_list * 2)
print("list Square: ", scores_list ** 2)'''


Array + 10: [33 43 74 98 66]
Array * 2:  [ 46  66 128 176 112]
array Square:  [ 529 1089 4096 7744 3136]


'scores_list = [23, 33,64, 88, 56]\n\nprint("list + 10:", scores_list + 10)\nprint("list * 2: ", scores_list * 2)\nprint("list Square: ", scores_list ** 2)'

In [ ]:
arr = np.array([23, 33,64, 88, 56])

print("Mean: ", np.mean(arr))
print("Median: ", np.median(arr))
print("Max: ", np.max(arr) )
print("Min: ", np.min(arr))
print("Sum: ", np.sum(arr))
print("Standard daviation: ", np.std(arr) )

Mean:  52.8
Median:  56.0
Max:  88
Min:  23
Sum:  264
Standard daviation:  23.04256930118688


In [ ]:
scores_list = [23, 33, 64, 88, 56]

scores_list_plus_10_loop = []
for x in scores_list:
    scores_list_plus_10_loop.append(x + 10)
print("List + 10 (using for loop):", scores_list_plus_10_loop)

In [ ]:
import numpy as np

class_a = np.array([49, 50, 51, 50, 52])
class_b = np.array([10, 30, 50, 80, 95])


print("Mean: ", np.mean(class_a))
print("Standard Daviation: ", np.std(class_a))
print("Mean: ", np.mean(class_b))
print("Standard Daviation: ", np.std(class_b))

Mean:  50.4
Standard Daviation:  1.0198039027185568
Mean:  53.0
Standard Daviation:  31.240998703626616


In [1]:
import numpy as np

# 1D array - one row of data
student_scores = np.array([78, 45, 91, 33, 85])
print("1D Array:", student_scores)
print("Shape:", student_scores.shape)

1D Array: [78 45 91 33 85]
Shape: (5,)


In [3]:
student = np.array([
    [23, 44, 53, 24],
    [55, 64, 35, 75],
    [87, 24, 54, 17]
])

print("2D array: ")
print( student)
print("Shape: ", student.shape)

2D array: 
[[23 44 53 24]
 [55 64 35 75]
 [87 24 54 17]]
Shape:  (3, 4)


In [4]:
students = np.array([
    [28, 33, 48],
    [18, 39, 78],
    [68, 63, 34]
])

print("Print the 1st row: ", students[0])
print("Print the 2nd row: ", students[1])
print("print the 1st column: ", students[:, 0])
print("Print specific element from the: ", students[2, 1])

Print the 1st row:  [28 33 48]
Print the 2nd row:  [18 39 78]
print the 1st column:  [28 18 68]
Print specific element from the:  63


In [5]:
marks = np.array([
    [56, 34, 77],
    [74, 33, 15],
    [88, 25, 56],
    [65, 24, 99]
])

print("full array: ", marks)
print("Third student marks: ", marks[2])
print("Second subject marks of all students: ", marks[:, 1])
print("Marks of student 2 subject 3: ", marks[1, 2])


full array:  [[56 34 77]
 [74 33 15]
 [88 25 56]
 [65 24 99]]
Third student marks:  [88 25 56]
Second subject marks of all students:  [34 33 25 24]
Marks of student 2 subject 3:  15


In [9]:
import pandas as pd
import numpy as np

marks = np.array([
    [56, 34, 77],
    [74, 33, 15],
    [88, 25, 56],
    [65, 24, 99]
])

df_marks = pd.DataFrame(
    marks,
    index=['Ali', 'Sara', 'Sohaib', 'Ahmed'],
    columns=['Science', 'Maths', 'Urdu']
)

print(df_marks)

        Science  Maths  Urdu
Ali          56     34    77
Sara         74     33    15
Sohaib       88     25    56
Ahmed        65     24    99


In [10]:
marks = np.array([
    [56, 34, 77],
    [74, 33, 15],
    [88, 25, 56],
    [65, 24, 99]
])

print("Average per student: ", np.mean(marks, axis=1))
print("Average per subject: ", np.mean(marks, axis=0))
print("Average marks: ", np.max(marks))
print("Highest per subject: ", np.max(marks, axis=0))

Average per student:  [55.66666667 40.66666667 56.33333333 62.66666667]
Average per subject:  [70.75 29.   61.75]
Average marks:  99
Highest per subject:  [88 34 99]


Alternatively, you could use a traditional `for` loop to achieve the same result: